### ISSUE TITLE
Popup gets cutoff.

### ISSUE THREAD

**Issue by avinashkanaujiya** [ananthakumaran/paisa#101]
When we hover the expenses categories in home, the popup get's cutoff, if items are more than 5 or more.

Maybe show a persistent popup, which user can scroll over, or dynamic list that scrolls itlsef, when user moves mouse pointer up or down on the list.

**Comment by ananthakumaran** [comment]
@avinashkanaujiya could you post a screenshot? You can use hide numbers to hide actual values

**Comment by avinashkanaujiya** [comment]
![IMG_0936](https://github.com/ananthakumaran/paisa/assets/24972285/fecc6c39-1ba3-4dfc-98d8-b3adf66aec05)

**Comment by avinashkanaujiya** [comment]
in the above image, the popup is supposed to have about 10 to 15 transactions, but I can only see about bottom 7 to 8.

**Comment by ananthakumaran** [comment]
I am having trouble reproducing the issue. For me, the tooltip is shown at the bottom if there is not enough space at the top to show it, I tried it on both Chrome and Firefox.

**Comment by avinashkanaujiya** [comment]
For me it is only happening for Food category, for rest it is working as it supposed to, like popup shows below, if not enough space at top. 

And I just tested with full screen, it is working fine there. 

So issue is with non full screen and specific category(weird).

**Comment by ananthakumaran** [comment]
@avinashkanaujiya I made some changes, could you check if the issue is fixed on 0.5.9

**Comment by avinashkanaujiya** [comment]
It is fixed in the latest version, sorry for late update.
