### ISSUE TITLE
Support  change the highest level account name

### ISSUE THREAD

**Issue by teteko233** [ananthakumaran/paisa#106]
I am a hledger user and the Income account in hledger called revenues. I want to use revenues rather than Income. So  could Paisa can add a config so that I can match my current account name to the Paisa style account name?

In addition, I am Chinese. So I wish the top level account name in Paisa can support UTF-8 char or CJK char.

**Comment by teteko233** [comment]
Thanks for your respond! I am going to search some way like using `capture` directive in ledger or `alias` directive in hledger to replace some account name with the paisa style account name.

But It doesn't work. I am confused
![image](https://github.com/ananthakumaran/paisa/assets/52707233/55efbd1f-820d-4aee-b4ad-081fd4e5b5e8)

**Comment by ananthakumaran** [comment]
What doesn't work?

**Comment by ananthakumaran** [comment]
Got it. Paisa uses balance command in the editor page only and csv command to export the data, which is used on all the other pages. If csv command returns `Income`, then every other place would work.

**Comment by teteko233** [comment]
So the temporary solution about issue is using `alias` directive.

for hledger user, use `alias Revenues  = Income`

for other language user, use statement like `alias Vermögen = Assets`(German), `alias 资产 = Assets`(Chinese) and so on.

I will close the issue and paisa UI can be translated to other languages in the feature.
