### ISSUE TITLE
ERROR - You have not made any transactions.

### ISSUE THREAD

**Issue by avinashkanaujiya** [ananthakumaran/paisa#111]
![edited-Pasted image](https://github.com/ananthakumaran/paisa/assets/24972285/cd178f1e-4c13-4cdc-a646-0f12c9c1c379)

This is what I am seeing even though transaction s are there.

When I click on any link while staying on home(on other screens it works), nothing happens, but if i go to that link, again by copy pasting it, in address bar, it works.

Some calculations are breaking in home page.

Also recurring page is not showing any transactions, like nothing ever was added.

**Comment by ananthakumaran** [comment]
I would need some more info, could you open inspector (right click and select inspect) and check if there are any errors there? Please include the paisa version as well.

**Comment by avinashkanaujiya** [comment]
This is the error on homepage.
```
transaction_sequence.95c51b11.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'scheduled')
    at w (transaction_sequence.95c51b11.js:1:1650)
    at transaction_sequence.95c51b11.js:1:2814
    at an (utils.f4790ebb.js:8:7232)
    at Function.Gr [as map] (utils.f4790ebb.js:10:10109)
    at C (transaction_sequence.95c51b11.js:1:2805)
    at 2.6d537083.js:31:15938
```
This is the error on recurring page.
```
transaction_sequence.95c51b11.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'scheduled')
    at w (transaction_sequence.95c51b11.js:1:1650)
    at transaction_sequence.95c51b11.js:1:2814
    at an (utils.f4790ebb.js:8:7232)
    at Function.Gr [as map] (utils.f4790ebb.js:10:10109)
    at C (transaction_sequence.95c51b11.js:1:2805)
    at 12.87e8fc18.js:5:3352


12.87e8fc18.js:5 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '2023-12')
    at 12.87e8fc18.js:5:3563
    at an (utils.f4790ebb.js:8:7232)
    at Gr (utils.f4790ebb.js:10:10109)
    at Function._g [as flatMap] (utils.f4790ebb.js:10:9478)
    at utils.f4790ebb.js:8:25710
    at Li (utils.f4790ebb.js:8:7417)
    at yo (utils.f4790ebb.js:8:25677)
    at Vn.ag (utils.f4790ebb.js:10:9203)
    at Po.n.$$.update (12.87e8fc18.js:5:3617)
    at ct (scheduler.8e30511f.js:1:8538)
```

**Comment by ananthakumaran** [comment]
Looks like something is wrong with the way recurring transactions are handled. I haven't figured out what's gone wrong so far. You could speed out the process by sharing a bit more info. Could you comment  out the automatic transactions one by one and check which one is breaking the app? I would need the dates of those transactions along with the automatic transaction rule

**Comment by avinashkanaujiya** [comment]
sure, I will try that out.

**Comment by avinashkanaujiya** [comment]
how do I comment them?, or you meant removing them?

**Comment by ananthakumaran** [comment]
something like below, just put a `;` before the `=`

```
; = Expenses:Rent
    ; Recurring: Rent
```

**Comment by avinashkanaujiya** [comment]
ok, so it only happens when there are multiple transactions on same date

**Comment by avinashkanaujiya** [comment]
> something like below, just put a `;` before the `=`
> 
> ```
> ; = Expenses:Rent
>     ; Recurring: Rent
> ```

also this doesn't work, editor throws a error

**Comment by ananthakumaran** [comment]
Thanks for the info, I can reproduce the issue now. To confirm, do you have transactions on only one date? The issue occurs for me if I put all the transactions on the same date and no other transactions for that tag name.

**Comment by avinashkanaujiya** [comment]
I have 6 transactions, of which 3 happened on separate months/date, remaining happened on same date, yesterday.
