### ISSUE TITLE
Icon not visible on dark background

### ISSUE THREAD

**Issue by vishalnandagopal** [ananthakumaran/paisa#116]
Current icon on a dark/black background
![image](https://github.com/ananthakumaran/paisa/assets/61023404/8e09c143-c453-44bc-a2fa-383fd6c559b3)

Icon can have a white background like this
![image](https://github.com/ananthakumaran/paisa/assets/61023404/e31f2f6c-9a94-4485-9608-2029e07cc3fb)

`icon.ico` is the current windows icon. I have changed the icon of the paisa app by taking the SVG from the docs website to show how a white background might look like.

**Comment by vishalnandagopal** [comment]
If the white background icon looks okay, I can polish it a bit and submit a PR with that as the icon

**Comment by ananthakumaran** [comment]
Thanks for reporting, I will check if I can come up with a different color instead of black and white.

**Comment by vishalnandagopal** [comment]
Just added a white background attribute

![img](https://github.com/ananthakumaran/paisa/assets/61023404/1c7612c7-55bf-4f6f-ba52-cafc40a4f5e4)

**Comment by ananthakumaran** [comment]
@vishalnandagopal could you try the latest version, I have updated the logo.

**Comment by vishalnandagopal** [comment]
![image](https://github.com/ananthakumaran/paisa/assets/61023404/48a0b419-a203-4b6c-858a-36bd0a8b2c30)

Hey, sorry for the late reply. Looks great now. thanks for the quick fix!
