### ISSUE TITLE
Error using hledger to sync on Windows 11

### ISSUE THREAD

**Issue by jafin** [ananthakumaran/paisa#129]
**Describe your Environment**
OS: Windows 11 23H2
Paisa Version: 0.6.2
App Variant: Desktop

**Describe the bug**
Configured to use hledger, when I run Sync journal it errors with 

exec: "hledger" cannot run executable found relative to current directory
I copied hledger.exe into the same folder of paisa.exe. I also copied it to  c:\Users\<username>\Documents\paisa\

**To Reproduce**
1. Sync journal
2. See error

**Expected behavior**
Sync journal works

**Screenshots**

![image](https://github.com/ananthakumaran/paisa/assets/127927/67b88a28-4750-4b38-abdb-00ba1be25beb)

**Journal**

**Comment by ananthakumaran** [comment]
> I copied hledger.exe into the same folder of paisa.exe. 

This is not supported, golang explicitly forbids the execution of binary from the current folder. I would suggest moving the `hledger.exe` to one of the folders under `PATH`. You can run `echo $env:PATH` from powershell to find the list of folders.

**Comment by jafin** [comment]
@ananthakumaran I copied `hledger.exe` into an existing `PATH env folder`. Same error.
Also tried executing from within powershell, in case there was an issue with windows cmd shell. No change.

Any other suggestions?

**Comment by ananthakumaran** [comment]
@jafin did you delete the file (hledger.exe) from the folder where paisa.exe resides? if not can you share the error text assuming the text has changed?

**Comment by jafin** [comment]
@ananthakumaran  thank you that was my issue. Removing the exe from the folder corrected the problem
