### ISSUE TITLE
Cannot run on Archlinux AMD64

### ISSUE THREAD

**Issue by psamim** [ananthakumaran/paisa#13]
Hi,

I downloaded the release for linux-amd64, did `chmod u+x` and then run. I got:

```
bash: /usr/bin/paisa: No such file or directory
```

But the file is there:

```
$ which paisa
/usr/bin/paisa

$ file `which paisa`
/usr/bin/paisa: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /nix/store/bzd91shky9j9d43girrrj6vmqlw7x9m8-glibc-2.35-163/lib/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, Go BuildID=ppx4Ehjfvj-CNB53xu7s/9ZGYU2bZM1xA0cXd4EFI/QflLjt_j8aSugrnEKM4Y/uV3Qj3mc2auZq3cbb-1I, with debug_info, not stripped
```

I am not sure what is wrong here.
I am on Archlinux.

Is there a possibility that it is compiled for a different architecture?
Can you please provide steps to manually compile?

Thanks

**Comment by ananthakumaran** [comment]
can you try this one [paisa.zip](https://github.com/ananthakumaran/paisa/files/11886836/paisa.zip)

looks like interpreter is hardcoded and likely won't work outside of nixos/nix

**Comment by psamim** [comment]
Yes, this one works for me.

**Comment by ananthakumaran** [comment]
Thanks for the confirmation. I have fixed this in the latest release as well.
