### ISSUE TITLE
Issue in Asset>Balance after v0.5.7

### ISSUE THREAD

**Issue by sdhawade** [ananthakumaran/paisa#133]
**Describe your Environment**
OS: Windows 10/Synology NAS 920+
Paisa Version:  0.6.2
App variant : All (Desktop/Cli/Docker)

**Describe the bug**
Asset>Balance view does not render properly. this worked properly (atleast) in 0.5.7

**To Reproduce**
1. Go to Asset>Balance in the new version
2. See columns are cut (refer screenshot on older pasisa version and newer version

**Screenshots**
Old version
<img width="1920" alt="image" src="https://github.com/ananthakumaran/paisa/assets/8513435/88046d62-9d59-4fd7-9478-382312e6579b">

New Version
<img width="1907" alt="image" src="https://github.com/ananthakumaran/paisa/assets/8513435/c113bcf8-230e-4f50-a4d5-350a28e33b42">

**Journal**
NA

**Comment by sdhawade** [comment]
The clipping of the asset name is gone but the view is still not spanning the window, see attached. This is 0.6.5
<img width="1919" alt="image" src="https://github.com/ananthakumaran/paisa/assets/8513435/e14e52ae-d190-4494-8a18-8cc39a02d7ea">

**Comment by ananthakumaran** [comment]
This is expected. If the table spans the full width of the screen, then it would be hard to read and compare numbers, especially in 4k screens.
