### ISSUE TITLE
Expenses with different currencies

### ISSUE THREAD

**Issue by psamim** [ananthakumaran/paisa#14]
Hi,

Thanks for this wonderful program.

I got a question, it seems that everything is treated as they are in a single currency. For example I have my expenses in two different currencies. I also have lines in my ledger to set the prices (starting with `P`) but it seems that in the expenses page all are treated as if they are in the same currency. Am I right?

**Comment by ananthakumaran** [comment]
Paisa has the concept of `default_currency` (check the [config doc](https://ananthakumaran.in/paisa/config.html)) and all the visualizations are shown in them. It does support multiple commodities. They are automatically converted to the default currency wherever necessary.

> I also have lines in my ledger to set the prices (starting with P)

P is not handled as of now. It only supports the 10 XYZ @ 5 USD format. I can add support for this.

I have not tested with multiple currencies so far. I have only tried with a single currency and multiple commodities. Please share a minimal example, so I can get a better understanding of your use case.

**Comment by psamim** [comment]
I have my income in two currencies and have set `default_currency`. But the graphs are behaving all of the numbers as they are in the same currency. 

For example in the graph below, the two left months are in another currency than of the two right months:

![image](https://github.com/ananthakumaran/paisa/assets/1868679/0dd2e827-0888-4432-8c70-669e5c4d597e)

Should I add `@ X EUR` to all of the transactions so that it can convert the numbers? I can but it seems too much work as I have years of transactions. Maybe we can have this as a future feature request.

**Comment by ananthakumaran** [comment]
do you use hledger? Using ledger seems to work for me with the below sample

```
P 2023/05/01 00:00:00 USD 0.9 EUR

;; USD income
2023/05/01 Freelance Income
    Income:Freelance                        -100 USD
    Assets:Checking

P 2023/06/01 00:00:00 USD 0.95 EUR

2023/06/01 Freelance Income
    Income:Freelance                        -200 USD
    Assets:Checking


;; EUR income
2023/05/02 Fulltime
    Income:Fulltime                        -1000 EUR
    Assets:Checking

2023/07/01 Netflix
    Expenses:Entertainment                        25 USD
    Assets:Checking
```

**Comment by ananthakumaran** [comment]
Can you try the latest release? I have added some improvements to multi-currency handling

**Comment by psamim** [comment]
Yes, it seems that it has fixed the issue! Thanks indeed.

**Comment by chengdejerrylin** [comment]
> do you use hledger? Using ledger seems to work for me with the below sample
> 
> ```
> P 2023/05/01 00:00:00 USD 0.9 EUR
> 
> ;; USD income
> 2023/05/01 Freelance Income
>     Income:Freelance                        -100 USD
>     Assets:Checking
> 
> P 2023/06/01 00:00:00 USD 0.95 EUR
> 
> 2023/06/01 Freelance Income
>     Income:Freelance                        -200 USD
>     Assets:Checking
> 
> 
> ;; EUR income
> 2023/05/02 Fulltime
>     Income:Fulltime                        -1000 EUR
>     Assets:Checking
> 
> 2023/07/01 Netflix
>     Expenses:Entertainment                        25 USD
>     Assets:Checking
> ```

I am trying to use the price tracker with Yahoo to track the exchange rate for me, but the expense tab in the web UI does not know the rate (The ledger->price tab shows the rate from Yahoo). Is it possible to let the expense tab use the rate from the tracker instead of just the manual rate in the ledger (the line starting with P)?
