### ISSUE TITLE
Beancount file crashes Mac app

### ISSUE THREAD

**Issue by scubed** [ananthakumaran/paisa#146]
**Describe your Environment**
OS: Mac Sonoma (silicon)
Paisa Version: 0.6.3
App Variant: Desktop

**Describe the bug**
Tried to open with my beancount file, which works fine and also in fava. Immediately crashes with this error:

```
Paisa has encountered a critical error and needs to close.
sql: converting argument $11 type: uint64 values with high bit set are not supported
File: /Users/runner/work/paisa/paisa/internal/model/posting/posting.go
Line: 123
Function:github.com/ananthakumaran/paisa/internal/model/posting.UpsertAll
```

The file that Paisa expects in Documents, is soft linked to my actual beancount file in another folder. Didn't want to have two copies floating around

**Comment by ananthakumaran** [comment]
would you be able to share a small ledger file that reproduces this issue? That would help me debug, without that it might be hard for me to figure out.

**Comment by scubed** [comment]
Hi could you tell me what you would need so I can prepare a small
version. The original file is pretty big.

It has a mix of assets, liabilities, expense accounts. Also quite a few
commodity and price directives and also beancount padding statements.

Thanks

**Comment by ananthakumaran** [comment]
I would suggest running paisa (cli not desktop app) in debug mode `PAISA_DEBUG=true paisa serve`, this will start to print the SQL queries directly to the console. Likely, it will give some hint about the location of the transaction that's breaking the app.

**Comment by scubed** [comment]
Ok, will try with the CLI and send you the debug output
