### ISSUE TITLE
Consider all amounts in multi-currency postings

### ISSUE THREAD

**Issue by adamantike** [ananthakumaran/paisa#150]
**Describe the bug**
For a transaction like:

```ledger
2024/01/01 Cash transfer
    Assets:Savings
    Assets:Checking                          -20,000 INR
    Assets:Checking                             -500 USD
```

The posting returned by `hledger` will have a list of two amounts in the JSON key `pamount`, for the `Assets:Savings` account. Currently, we are only considering the first one we find, so the one for USD is ignored.

Related pull request: #149

**Expected behavior**
Correctly create postings for all currencies involved.

**Comment by ananthakumaran** [comment]
Sorry about the PR, I added a pull request template so that others will get more warning (I have it in the readme, but it's easy to overlook).

I will check this issue soon.
