### ISSUE TITLE
Price does not update for some equities

### ISSUE THREAD

**Issue by sdhawade** [ananthakumaran/paisa#153]
**Describe your Environment**
OS: Windows 10
Paisa Version: 0.5.1
App Variant: CLI

**Describe the bug**
Proce for some commodities does not update. the data is present in the database but the prices view and market value used to compute markte value is the last one shown on the prices page

**To Reproduce**
Happens randomly for some stocks

**Expected behavior**
Expect updated data to be used

**Screenshots**
MID150BEES data only till 2nd May shown in prices page
<img width="1895" alt="image" src="https://github.com/ananthakumaran/paisa/assets/8513435/4d3ac589-d362-47c9-a004-d3bd2fdd105f">

Database has data till last trading day
<img width="776" alt="image" src="https://github.com/ananthakumaran/paisa/assets/8513435/8596fa9a-dfa6-4a1b-96ca-f3d126bfb3e0">

**Comment by ananthakumaran** [comment]
Could you double check the commodity name? There is an extra `_` in the commodity name shown in the database screenshot

**Comment by sdhawade** [comment]
<img width="815" alt="image" src="https://github.com/ananthakumaran/paisa/assets/8513435/cbb09613-0246-4939-9e6b-c565f2cea8f6">
This is the setting for the commodity name and stock code.

**Comment by sdhawade** [comment]
Ok got it thanks
