### ISSUE TITLE
Error while importing the password protected XLSX files.

### ISSUE THREAD

**Issue by swarajsomala** [ananthakumaran/paisa#156]
**Describe your Environment**
OS: Windows 11
Paisa Version: 0.6.3
App Variant:  CLI

**Describe the bug**
I encountered an issue when trying to import a XLSX file into Paisa after Paytm introduced a new password protection for its statements. The following error is being thrown:

![image](https://github.com/ananthakumaran/paisa/assets/24732012/be9b5f5e-7792-4db0-91ae-c94110ef4980)

**To Reproduce**
1. Go to 'Ledger->Import'
2. Click on 'Drag and Drop'
3. Choose the XLSX file.

**Expected behavior**
Paisa should show a popup so user can enter the password for the XLSX file.

**Screenshots**
![image](https://github.com/ananthakumaran/paisa/assets/24732012/387bd4d2-2a9b-4187-8263-f072fc0ce422)

**Comment by ananthakumaran** [comment]
@swarajsomala can you check the file extension? As I mentioned in the discussion thread, CSV file is just ascii characters and can't be password protected. Can you share the file extension? Windows explorer might be hiding the extension, you can use a powershell or other terminal to view it.

**Comment by ananthakumaran** [comment]
@swarajsomala I have pushed some changes to https://demo.paisa.fyi, can you try if that works for you?

**Comment by swarajsomala** [comment]
@ananthakumaran , Tested its working fine but I can see the password when I enter. Can you hide it?

![image](https://github.com/ananthakumaran/paisa/assets/24732012/9f96f2e7-f46e-4e22-9462-2cbc34711a31)

**Comment by swarajsomala** [comment]
Sure it’s good to have feature. Implement whenever you have some bandwidth, Thanks for adding the support.

**Comment by ananthakumaran** [comment]
This is now available on 0.6.5
