### ISSUE TITLE
Not able to install binary on Mac

### ISSUE THREAD

**Issue by shivprakashyadav** [ananthakumaran/paisa#16]
On the asset page I am not able to download for Mac .. pls let me know how to get for my Mac

**Comment by ananthakumaran** [comment]
You can download the mac binary from the latest release page https://github.com/ananthakumaran/paisa/releases/tag/v0.4.1. It's called paisa-darwin-amd64. You can follow the installation instruction on https://ananthakumaran.in/paisa/installation.html.

If you still not able to install, share more details like What you have tried so far, what step fails etc.
