### ISSUE TITLE
Two columsn in home are overlapping

### ISSUE THREAD

**Issue by avinashkanaujiya** [ananthakumaran/paisa#161]
![Pasted image](https://github.com/ananthakumaran/paisa/assets/24972285/8e425774-f5c1-48bb-a933-fd0a21814c1e)

**Comment by ananthakumaran** [comment]
@avinashkanaujiya would you be able to test the latest master? https://github.com/ananthakumaran/paisa/commit/aca11d7784998bb8910b0532928111e25f97c0ad is supposed to fix this problem.

**Comment by montogeek** [comment]
I can confirm that the latest release fixes this issue.

**Comment by ananthakumaran** [comment]
@avinashkanaujiya could you try 0.6.5, this issue should be solved there.

**Comment by avinashkanaujiya** [comment]
Yup, it has. Thanks for the great work.
