### ISSUE TITLE
Formatting errors in ledger file includes

### ISSUE THREAD

**Issue by jasperrooduijn** [ananthakumaran/paisa#170]
When using this transaction in `main.ledger` file syncing the journal is fine. But when using the same transaction inside an include file which is included in the `main.ledger` it's not possible to sync the journal.

`main.ledger` looks like this:

```
include accounts/account-a.ledger 
```

`account-a.ledger ` looks like:

```
2024/01/20 Opening Balances
    Assets:Checking:A               € 0.00
    Equity:OpeningBalances
```

The following error is thrown:

```
Paisa
Failed to sync

  Assets:Checking:A               € 0.00
                                                  ^^^^^^^^
Error: Incorrect use of thousand-mark period
```

**Comment by ananthakumaran** [comment]
@jasperrooduijn do you have any commodity directive in the main file or any other files? There is one edge case that is not handled as of today. If you have a commodity directive on the main file, but the subfile doesn't have it, it will work when you validate the main file, but the subfile might not be valid (if tested in isolation). Paisa validates each file in isolation, I think I need to always validate the main file and show errors related to the current file to avoid this problem.

**Comment by jasperrooduijn** [comment]
Thanks for the quick reply!

> do you have any commodity directive in the main file or any other files
No. The files as shown above is whats inside.

My config settings are the following:

<img width="499" alt="image" src="https://github.com/ananthakumaran/paisa/assets/1854745/b121ca18-d60d-4311-8ccc-d91911090c02">
<img width="499" alt="image" src="https://github.com/ananthakumaran/paisa/assets/1854745/8da835a3-d9eb-470e-8ee2-6d8a7a5f9335">

I just tested it again and found some extra information. The error only occurs when i edit my ledger files in VSC and sync the journal afterwards. If i edit them in the Paisa editor and save they will be saved without error. To summarise the `Incorrect use of thousand-mark period` error only occurs when saving a value like `€ 0.00` in a imported ledger file, when edited in VSC and synced afterwards.

Seems like an edge case, but as a developer i'm more keen in editing the ledger files in my VSC editor.

**Comment by ananthakumaran** [comment]
I am unsure if this has to do anything with using `EUR` as the default currency but using `€` in the ledger file. But I don't know how that could result in the above error.

**Comment by jasperrooduijn** [comment]
This seems to be something related to Ledger CLI and not specific to Paise. I will take a deeper dive later and will let you know.

**Comment by jasperrooduijn** [comment]
This can be closed. It was not related to Paisa. Thanks for helping.
