### ISSUE TITLE
Failed to build Dockerfile

### ISSUE THREAD

**Issue by Sinderella** [ananthakumaran/paisa#177]
**Describe your Environment**
OS: Linux
Paisa Version: master branch (62401a43d4affb76c557339aea3972da90ee9b36)
App Variant: Docker

**Describe the bug**
Failed to build Dockerfile

**To Reproduce**
Build the image, and I've got the message below. Probably due to old version of go? Switching to go 1.21 does fix the error.

**Expected behavior**
Build the image successfully

**Screenshots**
I've got log instead.

```
 => ERROR [go 8/8] RUN CGO_ENABLED=1 go build                                                                                                                                          99.0s
------
 > [go 8/8] RUN CGO_ENABLED=1 go build:
#0 98.03 # github.com/ananthakumaran/paisa/internal/ledger
#0 98.03 internal/ledger/ledger.go:394:28: undefined: max
#0 98.03 note: module requires Go 1.21
------
failed to solve: executor failed running [/bin/sh -c CGO_ENABLED=1 go build]: exit code: 1
```

**Journal**
n/a

**Comment by ananthakumaran** [comment]
Thanks for reporting, I upgraded go yesterday, seems like I missed the Dockerfile
