### ISSUE TITLE
Error calculating Market value in Asset->Balance

### ISSUE THREAD

**Issue by sdhawade** [ananthakumaran/paisa#18]
Getting an error in the Market value calculation in Asset->balance

**To Reproduce**
1. Create 2 transactions as below
2018/03/28 Purchase-NFO Purchase
     Assets:Debt:MF:HDFC_Mutual_Fund:FMP_XXXIX_1177D		50000.0000 "HDFC_FMP_XXXIX_1177D" @ 10.0000 INR
     Assets:Checking:HDFC

2021/06/16 Redeem-Direct Credit - HDFC
     Assets:Debt:MF:HDFC_Mutual_Fund:FMP_XXXIX_1177D		-50000.000 "HDFC_FMP_XXXIX_1177D" @ 12.9390 INR
     Assets:Checking:HDFC
2. Ledger shows correct balance 
 INR146950  Assets:Checking:HDFC
 
4.Navigating to Assets-Balance shows wrong value for market value (-1,46,950) correct value should zero as there is no asset held

5. Checking application log shows 
WARN xirr cannot be calculated

**Screenshots**
![Screenshot 2023-08-19 215855](https://github.com/ananthakumaran/paisa/assets/8513435/18e1df03-93d7-4a5e-8af0-1d82feea9f63)

**Comment by ananthakumaran** [comment]
Thanks for reporting the issue with a clear example. I am able to reproduce and the issue was due to the double quotes in the commodity name. It was not handled properly, I pushed a fix for it to the master branch. 

![image](https://github.com/ananthakumaran/paisa/assets/149238/65c3b4ed-06c6-4bad-bad9-9d40506f55fb)

Would you be able to build master? if not, let me know. I will release a new version soon.

**Comment by ananthakumaran** [comment]
I created a pre-release https://github.com/ananthakumaran/paisa/releases/tag/v0.4.8-rc1 with the bug fix.

**Comment by sdhawade** [comment]
> Thanks for reporting the issue with a clear example. I am able to reproduce and the issue was due to the double quotes in the commodity name. It was not handled properly, I pushed a fix for it to the master branch.
> 
> ![image](https://user-images.githubusercontent.com/149238/261814379-65c3b4ed-06c6-4bad-bad9-9d40506f55fb.png)
> 
> Would you be able to build master? if not, let me know. I will release a new version soon.

Thanks !! will pull and build, let  you know how it goes

**Comment by sdhawade** [comment]
Thanks for the fix, that issue got fixed, however for another case the xirr is not getting calculated (see attached) for the following transactions
2006/11/01 Switch In-Switch-In - From HDFC Floating Rate IF-Short Term(Growth)
    Assets:Equity:MF:HDFC_Mutual_Fund:HDFC_Core_and_Satellite_Fund_Growth		581.5980 "HDFC_Core_and_Satellite_Fund_Growth" @ 25.7910 INR
    Assets:Checking:HDFC

2006/12/01 Switch In-Switch-In - From HDFC Floating Rate IF-Short Term(Growth)
    Assets:Equity:MF:HDFC_Mutual_Fund:HDFC_Core_and_Satellite_Fund_Growth		560.9150 "HDFC_Core_and_Satellite_Fund_Growth" @ 26.7420 INR
    Assets:Checking:HDFC

2007/01/02 Switch In-Switch-In - From HDFC Floating Rate IF-Short Term(Growth)
    Assets:Equity:MF:HDFC_Mutual_Fund:HDFC_Core_and_Satellite_Fund_Growth		560.3920 "HDFC_Core_and_Satellite_Fund_Growth" @ 26.7670 INR
    Assets:Checking:HDFC

2007/02/01 Switch In-Switch-In - From HDFC Floating Rate IF-Short Term(Growth)
    Assets:Equity:MF:HDFC_Mutual_Fund:HDFC_Core_and_Satellite_Fund_Growth		561.0620 "HDFC_Core_and_Satellite_Fund_Growth" @ 26.7350 INR
    Assets:Checking:HDFC

2007/03/01 Switch In-Switch-In - From HDFC Floating Rate IF-Short Term(Growth)
    Assets:Equity:MF:HDFC_Mutual_Fund:HDFC_Core_and_Satellite_Fund_Growth		607.4600 "HDFC_Core_and_Satellite_Fund_Growth" @ 24.6930 INR
    Assets:Checking:HDFC

2007/04/02 Switch In-Switch-In - From HDFC Floating Rate IF-Short Term(Growth)
    Assets:Equity:MF:HDFC_Mutual_Fund:HDFC_Core_and_Satellite_Fund_Growth		638.8690 "HDFC_Core_and_Satellite_Fund_Growth" @ 23.4790 INR
    Assets:Checking:HDFC

2007/05/03 Switch In-Switch-In - From HDFC Floating Rate IF-Short Term(Growth)
    Assets:Equity:MF:HDFC_Mutual_Fund:HDFC_Core_and_Satellite_Fund_Growth		73.4460 "HDFC_Core_and_Satellite_Fund_Growth" @ 26.1010 INR
    Assets:Checking:HDFC	

2016/10/24 Redeem-Redemption - Direct Credit - HDFC , less STT
       Assets:Equity:MF:HDFC_Mutual_Fund:HDFC_Core_and_Satellite_Fund_Growth			-3583.742 "HDFC_Core_and_Satellite_Fund_Growth" @ 66.7720 INR
    Assets:Checking:HDFC
	
![Screenshot 2023-08-20 133059](https://github.com/ananthakumaran/paisa/assets/8513435/e4bf9186-3c89-4c4f-8df4-dfb5386cbcd4)

**Comment by ananthakumaran** [comment]
I have pushed another fix to master, give it a try.

**Comment by sdhawade** [comment]
> I have pushed another fix to master, give it a try.

Works like a charm, thanks again closing the issue.
