### ISSUE TITLE
Budgets not working

### ISSUE THREAD

**Issue by Noisycall** [ananthakumaran/paisa#185]
**Describe your Environment**
OS: Ubuntu 22.04
Paisa Version: 0.6.6
App Variant: CLI

**Describe the bug**
The budgets page does not show anything despite configuring budgets

**To Reproduce**
1. Add a periodic budget entry (of any kind, something as simple as `~ Monthly`)
2. Save the ledger
3. Navigate to Expenses>Budget
4. Shows that I need to configure budgets

**Expected behavior**
Should be able to see the budgets that I had configured

**Screenshots**
Main Budget
![image](https://github.com/ananthakumaran/paisa/assets/45820995/1259383e-eb67-4d40-8473-90a7607502c3)

Budget Page
![image](https://github.com/ananthakumaran/paisa/assets/45820995/24e9c015-9752-4025-a9da-396ab31af038)

**Journal**
```
2024/02/01 Example Transaction
    Expenses	5000 INR
    Assets:Checking
~ Monthly
    Expenses                                   50000 INR
    Assets:Checking
```

**Comment by ananthakumaran** [comment]
@Noisycall could you try something similar to what's used in the demo. Also use something like `Expenses:Food`, I don't know if the issue is due to just using `Expenses` without any sub-account name.

![image](https://github.com/ananthakumaran/paisa/assets/149238/e50e14f7-9986-47c0-8ddc-0e3381a93e52)

**Comment by ananthakumaran** [comment]
I would suggest just using a generic name like `Expenses:All`, that would work out for your intended use case, assuming you are not interested in the breakdown. Supporting only the top level would be tricky and not worth the effort from my perspective as there is a clean workaround.

**Comment by Noisycall** [comment]
Cool. Makes sense.
Thanks again 👍🏻
