### ISSUE TITLE
Broken Nix Flake?

### ISSUE THREAD

**Issue by frisodubach** [ananthakumaran/paisa#197]
**Describe your Environment**
OS: NixOS 23.11
Paisa Version: 0.6.6
App Variant: CLI

**Describe the bug**
The Nix Flake seems to not work, as running:
`nix run github:ananthakumaran/paisa`
Leads to the error
`error: unable to execute '/nix/store/0b92fv9p4kz6f7a05msrbv0fk1v8xl7j-paisa-cli-0.6.6/bin/paisa-cli': No such file or directory`

**To Reproduce**
1. Run `nix run github:ananthakumaran/paisa` in terminal
2. Get error

**Expected behavior**
Application to load and run properly

I'm not too familiar with using nix-flakes, but I usually try and run a flake first to try out an application before committing to it. For this the `nix run` command is convenient, as it's practically the same as the `nix profile` command that is listed in the docs as the install method, except that it's non-persistent. 
This is particularly helpful as the non-declarative nature of the `nix profile` command sort of goes against the purpose of using nix anyway.

**Comment by ananthakumaran** [comment]
@frisodubach This seems to be due to binary name mismatch. I have added the proper meta, it should run now. You might have to clear the flake cache.

**Comment by frisodubach** [comment]
Works perfectly now! Thank you for the quick fix!
