### ISSUE TITLE
Errors in fetching Equity values with numbers in the name

### ISSUE THREAD

**Issue by sdhawade** [ananthakumaran/paisa#20]
Many stocks and ETFs have a number in their name (eg MON100, MID150BEES) creating an entry in the paisa.yaml as follows does not update the equity data
  - name: MID_150BEES_NS
    type: stock
    code: MID150BEES.NS
Current **workaround** is to use names without numbers (Eg replace numbers with roman equivalent)
  - name: MID_CLBEES_NS
    type: stock
    code: MID150BEES.NS
This works but this name is also used  in the transactions so they have to be "adjusted" as follows
2022/09/01 MID150BEES (INF204KB1V68) buy
    Assets:Equity:ZeroDha:MID150BEES              21 "MIDCLBEES_NS" @ 121.59 INR
    Assets:Checking:HDFC

**Comment by ananthakumaran** [comment]
I pushed another fix to master, which will go with the next release soon. I had not fixed the quoting issue in all the places correctly when you reported it last time.
