### ISSUE TITLE
Docs reference links are broken

### ISSUE THREAD

**Issue by swarajsomala** [ananthakumaran/paisa#24]
The reference links to the docs(budget, recurring) are broken.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to http://localhost:7500/expense/budget or http://localhost:7500/cash_flow/recurring
2. Click on docs

**Screenshots**
![image](https://github.com/ananthakumaran/paisa/assets/24732012/e61d3daf-95b8-41a2-acf7-761f362e29af)
![image](https://github.com/ananthakumaran/paisa/assets/24732012/0594db77-81fb-48d2-b690-a8b7911c1c81)

**Comment by ananthakumaran** [comment]
Just released a new version with a fix.

**Comment by swarajsomala** [comment]
>
