### ISSUE TITLE
HDFC Rupay Card Template

### ISSUE THREAD

**Issue by Mozenraath** [ananthakumaran/paisa#245]
[6529XXXXXXXXXX70_13-06-2024 - Copy.PDF](https://github.com/user-attachments/files/15902683/6529XXXXXXXXXX70_13-06-2024.-.Copy.PDF)
Hi,
it would be great if you can support to create the template for Rupay credit card. I tried with existing templates but was not successful getting rid of invalid dates.

Much appreciated.

**Comment by ananthakumaran** [comment]
```mustache
{{#if (isDate (regexpMatch ROW.A "\s*(\d{2}/\d{2}/\d{4}).*" group=1) "DD/MM/YYYY")}}
  {{date (regexpMatch ROW.A "\s*(\d{2}/\d{2}/\d{4}).*" group=1) "DD/MM/YYYY"}} {{ROW.B}}
  {{#if (eq (trim ROW.D) "Cr")}}
    Income:Refund:CreditCard:HDFC             -{{trim ROW.C}} INR
  {{else}}
    {{predictAccount prefix="Expenses"}}      {{trim ROW.C}} INR
  {{/if}}
  Liabilities:CreditCard:Rupay
{{/if}}
```

give this a try

**Comment by Mozenraath** [comment]
Worked perfectly..
Thanks a lot.
