### ISSUE TITLE
Dashboard crashes

### ISSUE THREAD

**Issue by AgileSenthil** [ananthakumaran/paisa#252]
OS: Win 11 Home
App: Desktop version latest.

Action done:
Added one more ledger and synched the ledgers.

When I opened the dashboard I got the below error.

Workaround:
1. Deleted Paisa.db
2. Started the app and went to editor. 
3. Synched the ledgers.
4. I tested few menu options except the Dashboard. No issues.
5. When I clicked on Dashboard. I got the below error. The screen is not responsive. i.e. I am not able to close the error window and navigate to other menu options.

<img width="650" alt="image" src="https://github.com/ananthakumaran/paisa/assets/174768444/11c0cf1b-1c07-46da-97de-41d5bfc6befb">

**Comment by devzspy** [comment]
Duplicate of #249 

Take a look at my messing around @AgileSenthil and let me know if you have something similar

**Comment by AgileSenthil** [comment]
Let me close this issue as this is duplicate of #249
