### ISSUE TITLE
Changes in editor are lost if not explicitly saved

### ISSUE THREAD

**Issue by fimdomeio** [ananthakumaran/paisa#26]
**Describe the bug**
The Ledger editor should automatically save the file. If user makes edits and changes views without saving, changes are lost.

**To Reproduce**
1. Go to Ledger / Editor
2. Make a change
3. Click on Paisa main page

**Expected behavior**
As a user I was expecting file to be automatically saved or a warning before leaving the page, not for changes to be lost.

thank you for your work and making it open source.

**Comment by ananthakumaran** [comment]
This is fixed on  master. Please re-open if I haven't covered any cases where it's possible to lose edits.
