### ISSUE TITLE
Bug: Unable to select Tags when creating new expenses and incomes

### ISSUE THREAD

**Issue by theamallalgi** [ananthakumaran/paisa#309]
Issue: manually created a bunch of tags from the homepage, and when trying to add a new expense or even an income, selecting a tag seems to do nothing, a selected indicator does not appear like with the categories, the tags section shows 0 transactions too.

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified TransactionCard.svelte to include tag display and selection functionality. Added a new component for displaying tags, implemented tag selection logic, and updated the UI to show selected tags.

You can review changes in this commit: https://github.com/mnmnk43434/ananthakumaran-paisa-309/commit/a95af1b990f0710218a9ec3289d5d7e2bfdc7c77.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
