### ISSUE TITLE
Feat: More Import operators

### ISSUE THREAD

**Issue by brasilikum** [ananthakumaran/paisa#31]
As mentioned in Matrix, I would like to have access to more logic operators in the import.

Specifically:
- contains / substring / startswith: My bank does a lot of "Transaction from ***", "Interest for ***"
- greater than / less than: I do a lot of small transactions I would like to categorize into "general"
- regexpExtract: Extract account numbers / recipients from fields

**Comment by avinashkanaujiya** [comment]
Where can learn about this logic operators?

**Comment by ananthakumaran** [comment]
@avinashkanaujiya checkout https://paisa.fyi/reference/import/ and https://handlebarsjs.com/

@brasilikum I have added the last 2 items to master, regarding the first item contains, substring, etc. can you use the regexpTest helper?

**Comment by brasilikum** [comment]
@ananthakumaran Yes, that works.
I think there is an argument to make for _contains_ as a common enough usecase to have some syntactic sugar, but ultimately you should decide what best fits your vision for this project.

Thanks for the additions. I will be able to check them out later today
