### ISSUE TITLE
Please add .nvmrc file

### ISSUE THREAD

**Issue by ginruh** [ananthakumaran/paisa#38]
Please add .nvmrc file. It helps with regard to which node version to use and will also help you because bugs may show with bleeding edge node js version or unsupported node versions. 

If my English had errors, sorry, English is not my first language.

Thanks.

**Comment by ananthakumaran** [comment]
I use nix flake for project development and the versions are pinned. For future questions like this, please use the discussions. Issue tracker is only for bugs.

https://github.com/ananthakumaran/paisa/blob/873c3c1ad3f3b5835c93f7f2dc2ce1bb16ec374b/shell.nix#L5-L15
