### ISSUE TITLE
Test cases failed to run

### ISSUE THREAD

**Issue by ginruh** [ananthakumaran/paisa#39]
**Describe your Environment**
OS: Ubuntu 22.04 (WSL 2)
Paisa Version: master branch

**Describe the bug**
3/5 tests are failing

- ``src/lib/search/parser/parser.test.ts``
```
    src/lib/search/parser/parser.test.ts:8:44 - error TS1343: The 'import.meta' meta-property is only allowed when the '--module' option is 'es2020', 'es2022', 'esnext', 'system', 'node16', or 'nodenext'.

    8 const caseDir = path.dirname(fileURLToPath(import.meta.url));
```

- ``src/lib/search_query_editor.test.ts``
```
SyntaxError: Cannot use import statement outside a module

       5 | import { placeholder } from "@codemirror/view";
       6 | import _ from "lodash";
    >  7 | import { writable } from "svelte/store";
         | ^
       8 | import {
       9 |   CompletionContext,
      10 |   autocompletion,

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1496:14)
      at Object.<anonymous> (src/lib/search_query_editor.ts:7:1)
      at Object.<anonymous> (src/lib/search_query_editor.test.ts:2:1)
```

- ``src/lib/import.test.ts``
```
  ● Test suite failed to run

    Cannot find module 'pdfjs-dist/build/pdf.worker.js?url' from 'src/lib/pdf.ts'

    Require stack:
      src/lib/pdf.ts
      src/lib/sheet.ts
      src/lib/import.test.ts

      1 | import * as pdfjs from "pdfjs-dist";
      2 | import type { TextItem } from "pdfjs-dist/types/src/display/api";
    > 3 | import pdfjsWorkerUrl from "pdfjs-dist/build/pdf.worker.js?url";
        | ^
      4 |
      5 | if (pdfjs.GlobalWorkerOptions) {
      6 |   pdfjs.GlobalWorkerOptions.workerSrc = pdfjsWorkerUrl;

      at Resolver._throwModNotFoundError (node_modules/jest-resolve/build/resolver.js:427:11)
```

**To Reproduce**
1. Run ``npm test``

**Expected behavior**
All tests should pass.

**Comment by ananthakumaran** [comment]
I have setup github actions and it runs on every commit. Refer the below file for how to run the test, you can find the latest test run here https://github.com/ananthakumaran/paisa/actions/runs/6291039458/job/17079034327#step:4:550

https://github.com/ananthakumaran/paisa/blob/873c3c1ad3f3b5835c93f7f2dc2ce1bb16ec374b/.github/workflows/test.yml#L16-L18

Please use the discussions for questions like this, issue tracker is reserved for tracking bugs.

**Comment by ginruh** [comment]
Now I get it, you are not running ``npm run test``, instead you are running ``NODE_OPTIONS=--experimental-vm-modules npm run test``.
