### ISSUE TITLE
`regexpMatch` helper doesn't work in Import

### ISSUE THREAD

**Issue by pashagolub** [ananthakumaran/paisa#54]
No matter what arguments passed to the helper, it just returns nothing

![image](https://github.com/ananthakumaran/paisa/assets/9463113/020268e2-e9af-41db-bcfd-4d8ffe654c57)

I'm wondering, since it's not colorized, maybe it's not enabled?

**Comment by ananthakumaran** [comment]
sorry, it's on master, not yet released. I should stop publishing docs before release.

**Comment by pashagolub** [comment]
Just a side note. I found putting the first line as `; {{ROW.index}}` very convenient during Import. This way one can easily see which rows are missing

**Comment by pashagolub** [comment]
What command may one execute to build binary from master for tests? Is `make serve` enough?

**Comment by ananthakumaran** [comment]
It varies based on OS. You can look at how I am doing the release https://github.com/ananthakumaran/paisa/tree/master/.github/workflows and follow that. I am building ledger from source, you can ignore that and directly install it via package manager.
