### ISSUE TITLE
Fatal Error When Updating Mutual Fund Portfolios

### ISSUE THREAD

**Issue by dvo79** [ananthakumaran/paisa#61]
When attempting to update mutual fund portfolios or update commodity prices, I receive a fatal error. When selecting "Update Mutual Fund portfolios", the error is:

FATAL invalid character 'C' looking for beginning of value file=D:/a/paisa/paisa/internal/model/model.go:98func=github.com/ananthakumaran/paisa/internal/model.SyncPortfolios

When selecting "Update prices", the error is:
FATAL invalid character '<' looking for beginning of value file=D:/a/paisa/paisa/internal/model/model.go:71func=github.com/ananthakumaran/paisa/internal/model.SyncCommodities

I only have two commodities defined in the config file:

commodities:
    - name: FSMEX
      type: mutualfund
      price:
        provider: com-yahoo
        code: FSMEX
      harvest: 0
      tax_category: unlisted_equity
    - name: F
      type: stock
      price:
        provider: com-yahoo
        code: F
      harvest: 0
      tax_category: unlisted_equity

These functions appear to work normally when the F stock listing is the only one, but break when I attempt to add the FSMEX mutual fund listing.

Environment:
OS: Windows 10
Paisa Version: 0.5.2
App Variant: Desktop

**Comment by ananthakumaran** [comment]
Could you set the `type` to stock for now? I will fix the issue later, it tries to fetch the mutual fund data from different provider which fails.

**Comment by dvo79** [comment]
Ah, great, changing the type to stock seems to work - thanks!

**Comment by ananthakumaran** [comment]
It's a actual bug, I will keep it open till it's fixed
