### ISSUE TITLE
Support for "Else If"

### ISSUE THREAD

**Issue by dan335** [ananthakumaran/paisa#72]
Can {{else if something}} be added?

**Comment by ananthakumaran** [comment]
@dan335 have you tried it? it should work

**Comment by dan335** [comment]
It does.

I think why I thought it didn't is because "if" does not get highlighted.

![image](https://github.com/ananthakumaran/paisa/assets/499401/99249787-4222-4c41-93ca-ee5681165edc)

**Comment by ananthakumaran** [comment]
yeah, I missed that in the parser, will fix that.
