### ISSUE TITLE
Misplaced comma

### ISSUE THREAD

**Issue by rdaaron** [ananthakumaran/paisa#82]
Greetings. 
In your demo, any value over 99,999, the comma is shifted to the right one character. If 1 is added to this value, it should be 100,000. Instead, it's 1,00,000.

Another example in your investments view (https://demo.paisa.fyi/assets/investment)

AS-IS
Gross Salary Income	19,04,583
Gross Other Income	2,21,501
Tax	                      5,71,375
Net Income	15,54,709

SHOULD-Be
Gross Salary Income	1,904,583
Gross Other Income	221,501
Tax	                      571,375
Net Income	1,554,709

**Comment by ananthakumaran** [comment]
The demo is configured for INR currency with locale [en-IN](https://en.wikipedia.org/wiki/Indian_numbering_system). The numbers are formatted like `1,00,000`, 3 zeros followed by 2 zeros. If you came across this format for the first time this might look weird, but you can easily change this from the config page by setting the locale to `en-US`
