### ISSUE TITLE
Support for Unicode (for memo primarily)

### ISSUE THREAD

**Issue by nickdex** [ananthakumaran/paisa#93]
**Describe your Environment**
OS: Mac Ventura silicon
Paisa Version: 0.5.1
App Variant: Desktop

**Describe the bug**
Any unicode value in ledger will break Editor example
₹, ⓘ, characters with emphasis eg Nestlé

**To Reproduce**
1. Go to Editor
2. Copy paste any of these character
3. The tallied accounts on right will vanish and app won't let you save giving validation error

**Expected behavior**
Support for unicode

**Screenshots**
![Screenshot 2023-11-08 at 8 29 57 PM](https://github.com/ananthakumaran/paisa/assets/8512967/6d02c742-fc2f-48d9-9dd8-952c8b0fb5e6)

**Journal**
2020/01/01 Amazon Fresh ; Amazon:, Credit-Card:, Cancelled:
    ; Order ID: 4323
    ; Items:
    ; - Britannia 50-50 Biscuits, 40g
    ; - Nestlé MAGGI 2-minute Instant Noodles, Masala - 560g Pouch
    ; Initially charged to Amazon Pay ICICI Bank Credit Card
    Liabilities:Credit Card:ICICI Amazon      -604.0 INR
    Liabilities:Credit Card:ICICI Amazon       604.0 INR

Note - Something nice to have, not a showstopper but annoying since it doesn't point out line number so you have to manually scan each line of entire ledger. If you have bandwidth or maybe someone will fix it in next year's hacktoberfest

**Comment by ananthakumaran** [comment]
The error comes from the ledger cli. It does support UTF-8, provided the `LANG` env variable is set properly (example LANG=en_US.UTF-8). I am assuming Macos Desktop app is not setting any env variable (I have received a lot of reports related to this). To confirm, you can check if works via paisa-cli.

![image](https://github.com/ananthakumaran/paisa/assets/149238/b90ada8d-4b19-40a2-83f0-1a90f81de6be)

**Comment by ananthakumaran** [comment]
@nickdex could you check if the issue is fixed in the latest release 0.5.7

**Comment by nickdex** [comment]
It works now. Thank you! @ananthakumaran
